# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|
  config.vm.box = config.vm.box = "generic/oracle8"
  config.vm.provider "libvirt" do |hv|
    hv.cpus = 1
    hv.memory = 1048
  end


  config.vm.define "host1" do |host1|
    host1.vm.network :private_network, ip: "192.168.56.10"
    host1.vm.hostname = "debian-base"

    host1.vm.provision "shell", inline: <<-SHELL
      echo "VM TP – Debian Base" | sudo tee /etc/motd #Ajouter un message personnalisé dans /etc/motd
    SHELL
  end
end
