# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "bento/debian-13"
  config.vm.hostname = "demo-vagrant-debian"
  config.vm.network "private_network",
                    ip: "192.168.56.10"

  config.vm.provider "virtualbox" do |vb|
    # Nom de la VM tel qu’il apparaîtra dans l’interface VirtualBox
    vb.name = "debian-base"

    # Activer l'affichage graphique VirtualBox (false = mode "headless")
    vb.gui = false

    # Ressources matérielles
    vb.memory = 1024 # RAM en Mo
    vb.cpus   = 1     # nombre de vCPU

  
  end

end
