# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|
  # Box Oracle Linux 8 (provider libvirt)
  config.vm.box = "generic/oracle8"

  # Nom d'hôte
  config.vm.hostname = "lamp-server"

  # Réseau : port forwarding hôte 7676 -> VM 80
  config.vm.network "forwarded_port", guest: 80, host: 7676

  # Dossier partagé ./shared -> /var/www/html
  # owner/group www-data, fmode=644, dmode=755
config.vm.synced_folder "./shared", "/var/www/html",
  create: true,
  mount_options: ["dmode=755,fmode=644"]


  # (Optionnel) réglages spécifiques au provider libvirt
  config.vm.provider "libvirt" do |libvirt|
    libvirt.memory = 1024
    libvirt.cpus   = 1
  end

      config.vm.provision "shell", path: "PositionShell.sh"
  end